LocationSpawn:
  '1':
    x: -28
    y: 20
    z: 27
  '2':
    x: -28
    y: 20
    z: 8
  '3':
    x: -28
    y: 20
    z: -10
  '4':
    x: -28
    y: 20
    z: -29
  '5':
    x: -9
    y: 20
    z: -29
  '6':
    x: -9
    y: 20
    z: -10
  '7':
    x: -9
    y: 20
    z: 8
  '8':
    x: -9
    y: 20
    z: 27
  '9':
    x: 9
    y: 20
    z: 27
  '10':
    x: 9
    y: 20
    z: 8
  '11':
    x: 9
    y: 20
    z: -10
  '12':
    x: 9
    y: 20
    z: -29
  '13':
    x: 28
    y: 20
    z: -29
  '14':
    x: 28
    y: 20
    z: -10
  '15':
    x: 28
    y: 20
    z: 8
  '16':
    x: 28
    y: 20
    z: 27
